services:
  - type: web
    name: telegram-otp-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com
      - key: GROUP_ID
        value: -1001234567890
